Fix failed to compile build error due to missing type in `ErrorBoundary`
https://github.com/vtex-sites/nextjs.store/runs/6822439208
```
info - Checking validity of types...
Failed to compile.

./src/sdk/error/ErrorBoundary/ErrorBoundary.tsx:63:23
Type error: Property 'children' does not exist on type 'Readonly<{}>'.
```